{pkgs,...}:
{
    home.packages = (with pkgs; [
        #jdk
        jdk25_headless
        stockfish 
        cutechess 
        protontricks 
        wget 
        wget2 
        git-filter-repo 
        python315
        godot
        lua 
        libgcc 
        gcc 
        pkg-config 
        gdb 
        cmake 
        gnumake 
        neovim
        mariadb
        mosquitto
        mqttx
        nodejs_25
        nodePackages.node-red
        
        #libffi_3_3
        openssl
        pkg-config
        ]);
}
