{pkgs, ...}:
{
    home.packages = (with pkgs; [
        linuxConsoleTools
        blueman 
        opentabletdriver 
        mpv
        pavucontrol 
        inkscape 
        eog 
        mixxx
        audacity
        audacious
        orca-slicer
        kicad
        libreoffice-still
        anki-bin
        arduino
        vlc 
        prismlauncher
        spotify
        ungoogled-chromium
        xournalpp
        jetbrains-toolbox
        oversteer
        obs-studio
        usbview
        calibre
        protonplus
        twitch-dl
        nwg-displays
        antares
        cliphist
        wl-clipboard
        discord
        kdePackages.dolphin 
        kdePackages.konsole
        krita
        obsidian
        rnote
        ungoogled-chromium
        vesktop
        greenfoot
        eclipses.eclipse-java
        blockbench
        aseprite
        sfxr
        element-desktop
        qpwgraph
    ]);
}
